config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_view, name='index'),
    path('trabajo_final_grado/', include('trabajo_final_grado.urls', namespace='trabajo_final_grado')),

]

trabajo_final_grado/urls.py
from django.urls import path, include
from trabajo_final_grado.views import (trabajos,)

app_name = 'trabajo_final_grado'

urlpatterns = [
    path('', trabajos.IndexView.as_view(), name='index'),
    path('crear/', trabajos.CreateView.as_view(), name='create'),
    path('<int:id>/gestionar_tareas/', trabajos.ManageTasksView.as_view(), name='manage_tasks'),
    path('<int:id>/eliminar/', trabajos.DeleteTrabajoView.as_view(), name='delete'),
]

base/models.py
from django.db import models

# Create your models here.

trabajo_final_grado/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class TrabajoFinalGrado(models.Model):

    estados_trabajo = (
        (1, 'Creado' ),
    )
    estados_tareas = (
        (1, 'No gestionado'),
        (2, 'Gestionado')
        )

    nombre_trabajo = models.CharField('Nombre de trabajo de grado', max_length = 2000)
    descripcion = models.TextField('Descripción')
    equipo_de_trabajo = models.TextField('Equipo de trabajo')
    fecha_creacion = models.DateTimeField('Fecha creación', null=True, blank=True)
    planteamiento_del_problema = models.TextField('Planteamiento del problema', blank=True, null=True)
    identificacion_del_problema = models.TextField('Identificación del problema', blank=True, null=True)
    antecedentes_del_problema = models.TextField('Antecedentes', blank=True, null=True)
    estado = models.PositiveSmallIntegerField('Estado', choices=estados_trabajo, default=1)
    estado_tarea_uno = models.PositiveSmallIntegerField('Estado gestión 1', choices=estados_tareas, default=1)
    fecha_gestion_tarea_uno = models.DateTimeField('Fecha gestión tarea 1', null=True, blank=True)
    

    def save(self, *args, **kwargs):
        if self.id:
            #trabajo_existente = TrabajoFinalGrado.objects.get(id=self.id)
            if self.planteamiento_del_problema and self.identificacion_del_problema and self.antecedentes_del_problema and self.estado_tarea_uno == 1:
                self.estado_tarea_uno = 2
                self.fecha_gestion_tarea_uno = timezone.now()
        else:
            self.fecha_creacion = timezone.now()
        return super().save(*args, **kwargs)
                
    class Meta:
        verbose_name = "Trabajo final de grado"
        verbose_name_plural = "Trabajos finales de grado"

    def __str__(self):
        return self.nombre_trabajo

trabajo_final_grado/forms.py
from django import forms
from django.forms.widgets import TextInput
from django.forms import ValidationError, ModelForm, Form
from . import models

class TrabajoFinalGradoCreateForm(ModelForm):


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['descripcion'].widget.attrs['rows'] = 5
        self.fields['equipo_de_trabajo'].widget.attrs['rows'] = 5

    class Meta:
        model = models.TrabajoFinalGrado
        fields=['nombre_trabajo' , 'descripcion', 'equipo_de_trabajo']


class GestionarTareaform(ModelForm):


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['planteamiento_del_problema'].widget.attrs['rows'] = 5
        self.fields['identificacion_del_problema'].widget.attrs['rows'] = 5
        self.fields['antecedentes_del_problema'].widget.attrs['rows'] = 5

    class Meta:
        model = models.TrabajoFinalGrado
        fields=['planteamiento_del_problema' , 'identificacion_del_problema', 'antecedentes_del_problema']

base/views.py
from django.shortcuts import render

# Create your views here.

config/views.py
from django.shortcuts import redirect
from django.urls import reverse

def redirect_view(request):
    response = redirect(reverse('trabajo_final_grado:index'))
    return response

trabajo_final_grado/views.py
from django.shortcuts import render

# Create your views here.

trabajo_final_grado/views/trabajos.py
from django.shortcuts import render
from django.views.generic import View
from trabajo_final_grado import forms
from django.contrib import messages
from django.http import  HttpResponseRedirect
from django.urls import reverse
from trabajo_final_grado import models

class IndexView(View):

    def get(self, request):
        trabajos = models.TrabajoFinalGrado.objects.all()
        return render(request, 'trabajo_final_grado/trabajos/index.html', {
            'trabajos': trabajos
        })


class CreateView(View):

    template_name = 'trabajo_final_grado/trabajos/create.html'

    def get(self, request, *args, **kwargs):
        form = forms.TrabajoFinalGradoCreateForm()
        return render(request, self.template_name, {'form' : form})

    def post(self, request, *args, **kwargs):
        form = forms.TrabajoFinalGradoCreateForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Trabajo final de grado creado correctamente')
            return HttpResponseRedirect(reverse('trabajo_final_grado:index'))
        else:
            messages.error(request, 'Algo salió mal')
            return render(request, self.template_name, {'form' : form })


class ManageTasksView(View):

    template_name = 'trabajo_final_grado/trabajos/manage_taks.html'

    def get(self, request, id, *args, **kwargs):
        try:
            trabajo = models.TrabajoFinalGrado.objects.get(id=id)
        except models.TrabajoFinalGrado.DoesNotExist:
            messages.error(request, 'Trabajo final no encontrado')
            return HttpResponseRedirect(reverse('trabajo_final_grado:index'))
        
        form = forms.GestionarTareaform(instance=trabajo)
        return render(request, self.template_name, {
            'form' : form,
            'trabajo': trabajo})

    def post(self, request, id, *args, **kwargs):
        try:
            trabajo = models.TrabajoFinalGrado.objects.get(id=id)
        except models.TrabajoFinalGrado.DoesNotExist:
            messages.error(request, 'Trabajo final no encontrado')
            return HttpResponseRedirect(reverse('trabajo_final_grado:index'))
        form = forms.GestionarTareaform(instance=trabajo, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Tarea gestionada correctamente')
            return HttpResponseRedirect(reverse('trabajo_final_grado:index'))
        else:
            messages.error(request, 'Algo salió mal')
            return render(request, self.template_name, {
            'form' : form,
            'trabajo': trabajo})
        
class DeleteTrabajoView(View):

    template_name = 'trabajo_final_grado/trabajos/manage_taks.html'

    def get(self, request, id, *args, **kwargs):
        try:
            trabajo = models.TrabajoFinalGrado.objects.get(id=id)
        except models.TrabajoFinalGrado.DoesNotExist:
            messages.error(request, 'Trabajo final no encontrado')
        else:
            trabajo.delete()
            messages.success(request, 'Trabajo final de grado eliminado correctamente')
        return HttpResponseRedirect(reverse('trabajo_final_grado:index'))

base/templates/base.html
{% load static %}
<!DOCTYPE html>

<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#194278">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#194278">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#194278">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="icon" href="https://www.ucn.edu.co/exportes/ucn.ico" sizes="32x32">
  <title>{% block page_title %}UCN{% endblock page_title %}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/dist/css/adminlte.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/custom-skin.css' %}">
  
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  {% include 'partials/navbar.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'partials/sidebar.html' %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">

      {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>¡Éxito!</strong> {{ message|safe }}
              </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>¡Error!</strong> {{ message|safe }}
              </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>¡Advertencia!</strong> {{ message|safe }}
              </div>
            {% else %}
              <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Mensaje:</strong> {{ message|safe }}
              </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block header_title %}{% endblock header_title %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            {% block breadcrumb %}
            {% endblock breadcrumb %}
            <!-- <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol> -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


  <!-- Main Footer -->
  <footer class="main-footer">

    <span>
      <p><b>Ingeniería de Software - Ingeniería de Software I (Entregable 2)</b>
        <br>
        Equipo de trabajo:
      </p>
      <ul>
        <li>JUAN CARLOS DURANGO CORREA</li>
        <li>JUAN DAVID MARTINEZ SANTAMARIA</li>
        <li>JUAN PABLO MARTINEZ ZABALA</li>
        <li>OMAR CORTÉS MEDINA</li>
        <li>ANA MARIA MEJIA GUZMAN</li>
      </ul>
    </span>
    
    

    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      dev
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {% now "Y" %} <a href="https://www.ucn.edu.co/" target="blank_">UCN</a>.</strong> Todos los derechos reservados.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

  <!-- jQuery -->
  <script src="{% static 'AdminLTE-3.0.2/plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'AdminLTE-3.0.2/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'AdminLTE-3.0.2/dist/js/adminlte.min.js' %}"></script>

  <script src="{% static 'AdminLTE-3.0.2/plugins/datatables/jquery.dataTables.min.js' %}"></script>
</body>
</html>

base/templates/partials/field.html
{% load widget_tweaks %}
{% load base_tags %}
{% comment %} <script>console.log("{{field.html_name }} - {{field.field.widget.attrs.role_matrix|escapejs }}")</script> {% endcomment %}
{% if type == 'back-button' %}
    <a href="{% if back_url  %}{% url back_url  %}{% else %}{{ request.META.HTTP_REFERER }}{% endif %}" class="fa fa-chevron-left text-muted" data-html="true" data-placement="bottom" data-toggle="tooltip" data-original-title="Volver"></a>
{% else %}
    {% if form_type != "inline" %}
        <div class="form-group {% if field.errors %} has-error{% endif %}{% if hide %} hide{% endif %}">
    {% endif %}

    {% if not no_label %}
        {% if form_type == 'vertical' or form_type == 'inline' %}
            <label for="{{ field.auto_id }}">
        {% else %}
            <label class="text-right control-label" for="{{ field.auto_id }}">
        {% endif %}
        {% if not check_type == 'line' %}
            {% if field.field.help_text and not type == 'check' and not type == 'radio' %}
                <i class="fa fa-question-circle text-muted" title="{{ field.field.help_text }}" data-html="true" data-placement="top" data-toggle="tooltip" ></i>
            {% elif not help_text is None and not type == 'check' and not type == 'radio' %}
                <i class="fa fa-question-circle text-muted" title="{{ help_text }}" data-html="true" data-placement="top" data-toggle="tooltip" ></i>
            {% elif field.field.help_text and check_type == 'multi-switch' %}
                <i class="fa fa-question-circle text-muted" title="{{ field.field.help_text }}" data-html="true" data-placement="top" data-toggle="tooltip" ></i>
            {% endif %}

            {% if label_set is None %}{{field.label}}{% else %}{{label_set}}{% endif %}{% if field.field.required or type == 'choices_modal' or show_required %}<span class="text-required">*</span>{% endif %}
        {% endif %}

        </label>
    {% endif %}
        {% if form_type == 'vertical' %}
            <div>
        {% elif form_type == 'inline' %}
            <!-- nothing -->
        {% else %}
            <div>
        {% endif %}

            {% if not addon is None  %}
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa {{addon}}"></i>{% if addon == 'fa-phone' %} +57{% endif %}
                    </div>
            {% endif %}
            {% if type == 'label' or field.field.widget.attrs.role_matrix.readonlyhidden or readonly_internal %}
                {% comment %} <script>console.log("{{field.html_name }} - {{field.field.widget.attrs.role_matrix|escapejs }} - {{values_display}}")</script> {% endcomment %}
                <div class="form-control" style="background-color: #e8e8e85e;{% if type == 'textarea' %}height: auto;{% endif %}">{{ values_display|default:field.value|valdateformat|default:'No especificado' }}</div>{% comment %} {% format_values_display with field_value=field.value values_display=values_display %} {% endcomment %}
                <input type="hidden" name="{{ field.html_name }}" id="{{ field.auto_id }}" value="{{ field.value|default:'' }}">
            {% elif type == 'date' %}
                <input type="text" class="input-datepicker form-control" autocomplete="off" name="{{ field.html_name }}" id="{{ field.auto_id }}" {{ attr }} value="{% if field.value|field_type == 'str' %}{{ field.value }}{% else %}{{ field.value|date:'d/m/Y' }}{% endif %}" data-type="{{ field.value|field_type }}" placeholder="dd/mm/aaaa" {% if field.field.required %}required{% endif %}>
            {% elif type == 'check' %}
                {% if check_type == 'line'%}
                    <input type="checkbox" class="input-icheck" name="{{ field.html_name }}" id="{{ field.auto_id }}" {{ attr }} {% if field.value %}checked{% endif %} {% if field.field.required %}required{% endif %} {% if field.field.disabled %}disabled{% endif %}>
                    <label for="{{ field.auto_id }}">{% if label_set is None %}{{field.label}}{% else %}{{label_set}}{% endif %}</label>
                {% elif check_type == 'multi-switch'%}
                    <div class="row col-md-12">
                        <input type="checkbox" name="{{ field.html_name }}" id="{{ field.auto_id }}" class="multi-switch hide" {{ attr }} initial-value="1" {{ field.value|yesno:"checked,checked,''" }} checked-value="2" unchecked-value="3" value="{{ field.value|yesno:"2,3,1" }}" {% if field.field.required %}required{% endif %} {% if field.field.disabled %}disabled{% endif %}>
                    </div>
                {% else %}
                    <input type="checkbox" name="{{ field.html_name }}" id="{{ field.auto_id }}" {{ attr }} {% if field.value %}checked{% endif %} {% if field.field.required %}required{% endif %} {% if field.field.disabled %}disabled{% endif %}>
                {% endif %}
            {% elif type == 'radio' %}
                <input type="radio" name="{{ field.html_name }}" id="{{ field.auto_id }}">
            {% elif type == 'disabled' %}
                {{ field|add_class:"non-textarea form-control" | attr:"disabled"}}
            {% elif type == 'readonly' %}
                    {{ field|add_class:"non-textarea form-control" | attr:"readonly"}}
            {% elif type == 'multi-select2' %}
                {{ field|add_class:"input-select2" | attr:"multiple"}}
            {% elif type == 'time' %}
                <div class="bootstrap-timepicker input-group">
                    <input type="text" class="form-control input-timepicker" name="{{ field.html_name }}"  id="{{ field.auto_id }}"  value="{{ field.value }}" {% if field.field.required %}required{% endif %} >
                    <div class="input-group-addon">
                        <i class="fa fa-clock-o"></i>
                    </div>
                </div>
            {% elif type == 'datetime' %}
                <div class="input-group date datetimepicker">
                    <input type="text" class="form-control" name="{{ field.html_name }}"  id="{{ field.auto_id }}"  value="{{ field.value }}" {% if field.field.required %}required{% endif %} >
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                </div>
            {% elif type == 'file' %}
                {% if field.initial %}
                    <a href="{{ field.initial.url }}" target="blank" title="Ver archivo adjunto">
                        <i class="fa fa-paperclip fa-2x"></i>
                    </a>
                {% endif %}
                {{ field|add_class:"form-control form-file" }}
            {% elif type == 'select2' %}
              {% with attr as attrs %}
                {{ field|add_class:"input-select2 form-control"|attr:attrs }}
              {% endwith %}
            {% elif type == 'array' %}

                <table class="table table-condensed table-hover">
                    <tbody>

                        {% for value in field.initial %}

                            <tr id="{{ field.html_name}}_{{ forloop.counter }}">
                                <td class="col-md-11">
                                    <span>{{ value }}</span>
                                    <input type="hidden" name="{{ field.html_name }}" value="{{ value }}">
                                </td>
                                <td class="col-md-1">
                                    <button type="button" class="btn btn-xs btn-default btn-array-field-remove" data-row-array-field="#{{ field.html_name}}_{{ forloop.counter }}">
                                        <span class="fa fa-remove fa-lg text-red"></span>
                                    </button>
                                </td>
                            </tr>

                        {% endfor %}

                        <tr>
                                <td>
                                {# {% if form_functions.functions.field.widget.input_type == 'select' %} #}

                                    {# {{ field|add_class:"input-select2 form-control" }} #}

                                    <input type="text" class="form-control" name="{{ field.html_name }}_array_field_add">

                                {# {% endif %} #}

                            </td>
                            <td>
                                <button type="button" class="btn btn-xs btn-default btn-array-field-add" data-field-name='{{ field.html_name }}'>
                                    <span class="fa fa-plus fa-lg text-green"></span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>


            {% elif type == 'choices_modal' %}

                <div class="input-group">
                    {{ field|add_class:"form-control"|attr:"readonly"}}
                    <span class="input-group-btn">
                        <button class="btn btn-default {% if field.field.widget.attrs.disabled %}disabled{% endif %}" type="button" data-toggle="modal" data-target="#id_modal_{{ field.html_name }}" {% if field.field.widget.attrs.disabled %}disabled{% endif %} id="button_modal_{{ field.html_name }}">
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>

            {% elif type == 'textarea' %}

                <textarea class="form-control" rows="{{ rows }}" name="{{ field.html_name }}" id="{{ field.auto_id }}" placeholder="{{ field.help_text }}" {% if field.field.required %}required{% endif %}>{% if field.value %}{{ field.value }}{% endif %}</textarea>

            {% else %}
              {% with attr as attrs %}
                {{ field|add_class:"non-textarea form-control"|attr:attrs }}
              {% endwith %}
            {% endif %}

            {% if not addon is None %}
            </div>
            {% endif %}

            {% if field.field.help_text and type == 'check' and check_type != 'multi-switch' or type == 'radio' %}

                <span class="help-text">{{ field.field.help_text }}</span>

            {% endif %}

        {% if form_type != 'inline' %}
            </div>
        {% endif %}

        {% for error in field.errors %}
            <div class="text-danger">- {{ error }}</div>
        {% endfor %}

        {% if form_type != 'inline' %}
            </div>

        {% endif %}

{% endif %}

base/templates/partials/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index' %}" class="nav-link"><i class="fas fa-home"></i></a>
      </li>
    </ul>
  </nav>

trabajo_final_grado/templates/trabajo_final_grado/trabajos/create.html
{% extends 'base.html' %}

{% block header_title %} Trabajo final de grado {% endblock header_title %}

{% block content %}

<section class="content">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Crear trabajo final de grado</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Para crear un trabajo final de grado por favor diligencie los siguientes campos:</p>
                            <form method="POST">
                                {% csrf_token %}
                                {% include "partials/field.html" with field=form.nombre_trabajo %}
                                {% include "partials/field.html" with field=form.descripcion %}
                                {% include "partials/field.html" with field=form.equipo_de_trabajo %}
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary float-right" >Crear</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

{% endblock %}

trabajo_final_grado/templates/trabajo_final_grado/trabajos/index.html
{% extends 'base.html' %}

{% block header_title %} Trabajo final de grado {% endblock header_title %}

{% block content %}

<section class="content">
    <div class="row">
        <div class="col-8 col-sm-12"">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de trabajos finales de grado</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-3 col-lg-2">
                            <a href="{% url 'trabajo_final_grado:create' %}" class="btn btn-block bg-gradient-primary"><i class="fas fa-plus"></i> Nuevo trabajo de grado</a>
                        </div>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre de trabajo</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Equipo de trabajo</th>
                                <th scope="col">Estado</th>
                                <th scope="col">Fecha creación</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for trabajo in trabajos %}
                            <tr>
                                <th scope="row">{{ trabajo.id }}</th>
                                <td>{{ trabajo.nombre_trabajo }}</td>
                                <td>{{ trabajo.descripcion }}</td>
                                <td>{{ trabajo.equipo_de_trabajo|linebreaks }}</td>
                                <td>{{ trabajo.get_estado_display }}</td>
                                <td>{{ trabajo.fecha_creacion|date:'d/m/Y h:i a' }}</td>
                                <td>
                                    <a href="{% url 'trabajo_final_grado:manage_tasks' trabajo.id %}" class="btn btn-xs bg-gradient-info"><i class="fas fa-edit"></i> Gestionar tareas</a>
                                    <a href="{% url 'trabajo_final_grado:delete' trabajo.id %}" class="btn btn-xs bg-gradient-danger"><i class="fas fa-times"></i> Eliminar</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

{% endblock %}

trabajo_final_grado/templates/trabajo_final_grado/trabajos/manage_taks.html
{% extends 'base.html' %}

{% block header_title %} Trabajo final de grado {% endblock header_title %}

{% block content %}

<section class="content">
    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tarea 1: DEFINICIÓN DEL PROBLEMA ({{ trabajo.get_estado_tarea_uno_display }}{% if trabajo.fecha_gestion_tarea_uno %} - Fecha: {{ trabajo.fecha_gestion_tarea_uno|date:'d/m/Y h:i a' }}{% endif %})</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Diligencie los siguientes campos:</p>
                            <form method="POST">
                                {% csrf_token %}
                                {% include "partials/field.html" with field=form.planteamiento_del_problema %}
                                {% include "partials/field.html" with field=form.identificacion_del_problema %}
                                {% include "partials/field.html" with field=form.antecedentes_del_problema %}
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary float-right" >Guardar tarea</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Información de trabajo final</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <b>Nombre del trabajo: </b> <br>
                            {{trabajo.nombre_trabajo}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <b>Descripción: </b> <br>
                            {{trabajo.descripcion}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <b>Equipo de trabajo: </b> <br>
                            {{trabajo.equipo_de_trabajo|linebreaks}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <b>Estado: </b> <br>
                            {{trabajo.get_estado_display }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <b>Fecha de creación: </b> <br>
                            {{ trabajo.fecha_creacion|date:'d/m/Y h:i a' }}
                        </div>
                    </div>
                    
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

{% endblock %}